#include "shaders.h"
#include "../renderer.h"
#include "common/uniforms_wgsl.h"

static const char *kShaderSource =
    FLECS_ENGINE_SHADER_COMMON_UNIFORMS_WGSL
    "struct VertexInput {\n"
    "  @location(0) pos : vec3<f32>,\n"
    "  @location(1) nrm : vec3<f32>,\n"
    "  @location(2) m0 : vec3<f32>,\n"
    "  @location(3) m1 : vec3<f32>,\n"
    "  @location(4) m2 : vec3<f32>,\n"
    "  @location(5) m3 : vec3<f32>,\n"
    "  @location(6) color : vec4<f32>\n"
    "};\n"
    "struct VertexOutput {\n"
    "  @builtin(position) pos : vec4<f32>,\n"
    "  @location(0) clip_xy : vec2<f32>,\n"
    "  @location(1) color : vec4<f32>\n"
    "};\n"
    "struct FragOutput {\n"
    "  @location(0) color : vec4<f32>,\n"
    "  @builtin(frag_depth) depth : f32\n"
    "};\n"
    "const PLANE_Y : f32 = -0.002;\n"
    "@vertex fn vs_main(input : VertexInput) -> VertexOutput {\n"
    "  var out : VertexOutput;\n"
    "  let model = mat4x4<f32>(\n"
    "    vec4<f32>(input.m0, 0.0),\n"
    "    vec4<f32>(input.m1, 0.0),\n"
    "    vec4<f32>(input.m2, 0.0),\n"
    "    vec4<f32>(input.m3, 1.0)\n"
    "  );\n"
    "  let world_pos = model * vec4<f32>(input.pos, 1.0);\n"
    "  out.pos = vec4<f32>(world_pos.xy, 0.99999, 1.0);\n"
    "  out.clip_xy = out.pos.xy;\n"
    "  out.color = input.color;\n"
    "  return out;\n"
    "}\n"
    "@fragment fn fs_main(input : VertexOutput) -> FragOutput {\n"
    "  var out : FragOutput;\n"
    "  let clip_far = vec4<f32>(input.clip_xy, 1.0, 1.0);\n"
    "  let world_far_h = uniforms.inv_vp * clip_far;\n"
    "  let inv_w = select(1.0, 1.0 / world_far_h.w, abs(world_far_h.w) > 1e-5);\n"
    "  let world_far = world_far_h.xyz * inv_w;\n"
    "  let ray_origin = uniforms.camera_pos.xyz;\n"
    "  let raw_dir = world_far - ray_origin;\n"
    "  let ray_dir = select(\n"
    "    vec3<f32>(0.0, -1.0, 0.0),\n"
    "    normalize(raw_dir),\n"
    "    dot(raw_dir, raw_dir) > 1e-8\n"
    "  );\n"
    "  let denom = ray_dir.y;\n"
    "  if (denom >= -1e-6) {\n"
    "    discard;\n"
    "  }\n"
    "  let t = (PLANE_Y - ray_origin.y) / denom;\n"
    "  if (t < 0.0) {\n"
    "    discard;\n"
    "  }\n"
    "  let hit = ray_origin + t * ray_dir;\n"
    "  let clip_hit = uniforms.vp * vec4<f32>(hit, 1.0);\n"
    "  out.depth = clamp(clip_hit.z / clip_hit.w, 0.0, 0.99999);\n"
    "  let dist = length(hit - ray_origin);\n"
    "  let fade = exp(-dist * 0.0015);\n"
    "  if (fade < 0.001) {\n"
    "    discard;\n"
    "  }\n"
    "  let sky = uniforms.sky_color.rgb;\n"
    "  out.color = vec4<f32>(mix(sky, input.color.rgb, fade), 1.0);\n"
    "  return out;\n"
    "}\n";

ecs_entity_t flecsEngine_shader_infinitePlane(
    ecs_world_t *world)
{
    return flecsEngine_shader_ensure(world, "InfinitePlaneShader",
        &(FlecsShader){
            .source = kShaderSource,
            .vertex_entry = "vs_main",
            .fragment_entry = "fs_main"
        });
}
