#include "shaders.h"
#include "../renderer.h"

static const char *kShaderSource =
    "struct Uniforms {\n"
    "  vp : mat4x4<f32>,\n"
    "  clear_color : vec4<f32>,\n"
    "  light_ray_dir : vec4<f32>,\n"
    "  light_color : vec4<f32>,\n"
    "  camera_pos : vec4<f32>\n"
    "}\n"
    "@group(0) @binding(0) var<uniform> uniforms : Uniforms;\n"
    "struct GpuMaterial {\n"
    "  color : u32,\n"
    "  metallic : f32,\n"
    "  roughness : f32,\n"
    "  _pad : f32\n"
    "};\n"
    "@group(0) @binding(1) var<storage, read> materials : array<GpuMaterial>;\n"
    "const PI : f32 = 3.141592653589793;\n"
    "struct VertexInput {\n"
    "  @location(0) pos : vec3<f32>,\n"
    "  @location(1) nrm : vec3<f32>,\n"
    "  @location(2) m0 : vec3<f32>,\n"
    "  @location(3) m1 : vec3<f32>,\n"
    "  @location(4) m2 : vec3<f32>,\n"
    "  @location(5) m3 : vec3<f32>,\n"
    "  @location(6) material_id : u32\n"
    "};\n"
    "struct VertexOutput {\n"
    "  @builtin(position) pos : vec4<f32>,\n"
    "  @location(0) normal : vec3<f32>,\n"
    "  @location(1) world_pos : vec3<f32>,\n"
    "  @location(2) @interpolate(flat) material_id : u32\n"
    "};\n"
    "@vertex fn vs_main(input : VertexInput) -> VertexOutput {\n"
    "  var out : VertexOutput;\n"
    "  let model = mat4x4<f32>(\n"
    "    vec4<f32>(input.m0, 0.0),\n"
    "    vec4<f32>(input.m1, 0.0),\n"
    "    vec4<f32>(input.m2, 0.0),\n"
    "    vec4<f32>(input.m3, 1.0)\n"
    "  );\n"
    "  let model3 = mat3x3<f32>(input.m0, input.m1, input.m2);\n"
    "  let c0 = model3[0];\n"
    "  let c1 = model3[1];\n"
    "  let c2 = model3[2];\n"
    "  let normal_matrix = mat3x3<f32>(\n"
    "    cross(c1, c2),\n"
    "    cross(c2, c0),\n"
    "    cross(c0, c1)\n"
    "  );\n"
    "  let world_pos = model * vec4<f32>(input.pos, 1.0);\n"
    "  out.pos = uniforms.vp * world_pos;\n"
    "  out.normal = normalize(normal_matrix * input.nrm);\n"
    "  out.world_pos = world_pos.xyz;\n"
    "  out.material_id = input.material_id;\n"
    "  return out;\n"
    "}\n"
    "fn fresnelSchlick(cos_theta : f32, f0 : vec3<f32>) -> vec3<f32> {\n"
    "  return f0 + (vec3<f32>(1.0) - f0) * pow(1.0 - cos_theta, 5.0);\n"
    "}\n"
    "fn distributionGGX(n : vec3<f32>, h : vec3<f32>, roughness : f32) -> f32 {\n"
    "  let a = roughness * roughness;\n"
    "  let a2 = a * a;\n"
    "  let ndoth = max(dot(n, h), 0.0);\n"
    "  let ndoth2 = ndoth * ndoth;\n"
    "  let denom = ndoth2 * (a2 - 1.0) + 1.0;\n"
    "  return a2 / max(PI * denom * denom, 1e-4);\n"
    "}\n"
    "fn geometrySchlickGGX(ndotv : f32, roughness : f32) -> f32 {\n"
    "  let r = roughness + 1.0;\n"
    "  let k = (r * r) / 8.0;\n"
    "  return ndotv / max(ndotv * (1.0 - k) + k, 1e-4);\n"
    "}\n"
    "fn geometrySmith(\n"
    "  n : vec3<f32>,\n"
    "  v : vec3<f32>,\n"
    "  l : vec3<f32>,\n"
    "  roughness : f32) -> f32 {\n"
    "  let ndotv = max(dot(n, v), 0.0);\n"
    "  let ndotl = max(dot(n, l), 0.0);\n"
    "  let ggx_v = geometrySchlickGGX(ndotv, roughness);\n"
    "  let ggx_l = geometrySchlickGGX(ndotl, roughness);\n"
    "  return ggx_v * ggx_l;\n"
    "}\n"
    "struct DirectionSample {\n"
    "  dir : vec3<f32>,\n"
    "  enabled : bool\n"
    "};\n"
    "fn safeNormalize(v : vec3<f32>, fallback : vec3<f32>) -> vec3<f32> {\n"
    "  let len2 = dot(v, v);\n"
    "  return normalize(select(fallback, v, len2 > 1e-6));\n"
    "}\n"
    "fn getLightDirection() -> DirectionSample {\n"
    "  let light_vec = -uniforms.light_ray_dir.xyz;\n"
    "  let light_enabled = dot(light_vec, light_vec) > 1e-6;\n"
    "  return DirectionSample(safeNormalize(light_vec, vec3<f32>(0.0, 1.0, 0.0)), light_enabled);\n"
    "}\n"
    "fn getViewDirection(world_pos : vec3<f32>) -> vec3<f32> {\n"
    "  let view_vec = uniforms.camera_pos.xyz - world_pos;\n"
    "  return safeNormalize(view_vec, vec3<f32>(0.0, 0.0, 1.0));\n"
    "}\n"
    "fn getHalfVector(v : vec3<f32>, l : vec3<f32>) -> vec3<f32> {\n"
    "  return safeNormalize(v + l, v);\n"
    "}\n"
    "fn computeF0(albedo : vec3<f32>, metallic : f32) -> vec3<f32> {\n"
    "  return mix(vec3<f32>(0.04), albedo, metallic);\n"
    "}\n"
    "fn computeDiffuse(albedo : vec3<f32>, metallic : f32, f : vec3<f32>) -> vec3<f32> {\n"
    "  let kd = (vec3<f32>(1.0) - f) * (1.0 - metallic);\n"
    "  return kd * albedo / PI;\n"
    "}\n"
    "fn computeSpecular(\n"
    "  n : vec3<f32>,\n"
    "  v : vec3<f32>,\n"
    "  l : vec3<f32>,\n"
    "  h : vec3<f32>,\n"
    "  roughness : f32,\n"
    "  f : vec3<f32>) -> vec3<f32> {\n"
    "  let ndotv = max(dot(n, v), 0.0);\n"
    "  let ndotl = max(dot(n, l), 0.0);\n"
    "  let d = distributionGGX(n, h, roughness);\n"
    "  let g = geometrySmith(n, v, l, roughness);\n"
    "  let spec_num = d * g * f;\n"
    "  let spec_denom = max(4.0 * ndotv * ndotl, 1e-4);\n"
    "  return spec_num / spec_denom;\n"
    "}\n"
    "fn computeDirectLighting(\n"
    "  n : vec3<f32>,\n"
    "  v : vec3<f32>,\n"
    "  l : vec3<f32>,\n"
    "  h : vec3<f32>,\n"
    "  albedo : vec3<f32>,\n"
    "  metallic : f32,\n"
    "  roughness : f32,\n"
    "  light_active : bool) -> vec3<f32> {\n"
    "  if (!light_active) {\n"
    "    return vec3<f32>(0.0);\n"
    "  }\n"
    "  let ndotl = max(dot(n, l), 0.0);\n"
    "  if (ndotl <= 0.0) {\n"
    "    return vec3<f32>(0.0);\n"
    "  }\n"
    "  let f0 = computeF0(albedo, metallic);\n"
    "  let f = fresnelSchlick(max(dot(h, v), 0.0), f0);\n"
    "  let diffuse = computeDiffuse(albedo, metallic, f);\n"
    "  let specular = computeSpecular(n, v, l, h, roughness, f);\n"
    "  return (diffuse + specular) * uniforms.light_color.rgb * ndotl;\n"
    "}\n"
    "fn computeAmbientLighting(albedo : vec3<f32>, metallic : f32) -> vec3<f32> {\n"
    "  return albedo * 0.03 * (1.0 - metallic);\n"
    "}\n"
    "@fragment fn fs_main(input : VertexOutput) -> @location(0) vec4<f32> {\n"
    "  let material = materials[input.material_id];\n"
    "  let color = unpack4x8unorm(material.color);\n"
    "  let albedo = color.rgb;\n"
    "  let metallic = clamp(material.metallic, 0.0, 1.0);\n"
    "  let roughness = clamp(material.roughness, 0.045, 1.0);\n"
    "  let n = normalize(input.normal);\n"
    "  let light = getLightDirection();\n"
    "  let v = getViewDirection(input.world_pos);\n"
    "  let h = getHalfVector(v, light.dir);\n"
    "  let direct = computeDirectLighting(\n"
    "    n, v, light.dir, h,\n"
    "    albedo, metallic, roughness,\n"
    "    light.enabled);\n"
    "  let ambient = computeAmbientLighting(albedo, metallic);\n"
    "  let lit_color = ambient + direct;\n"
    "  return vec4<f32>(lit_color, color.a);\n"
    "}\n";

ecs_entity_t flecsEngineShader_pbrColoredMaterialIndex(
    ecs_world_t *world)
{
    return flecsEngineEnsureShader(world, "PbrColoredMaterialIndexShader",
        &(FlecsShader){
            .source = kShaderSource,
            .vertex_entry = "vs_main",
            .fragment_entry = "fs_main"
        });
}
