#include "shaders.h"
#include "../renderer.h"
#include "common/shared_vertex_wgsl.h"
#include "common/pbr_functions_wgsl.h"

static const char *kShaderSource =
    "struct Uniforms {\n"
    "  vp : mat4x4<f32>,\n"
    "  inv_vp : mat4x4<f32>,\n"
    "  clear_color : vec4<f32>,\n"
    "  light_ray_dir : vec4<f32>,\n"
    "  light_color : vec4<f32>,\n"
    "  camera_pos : vec4<f32>\n"
    "}\n"
    "@group(0) @binding(0) var<uniform> uniforms : Uniforms;\n"
    "@group(1) @binding(0) var ibl_prefiltered_env : texture_cube<f32>;\n"
    "@group(1) @binding(1) var ibl_sampler : sampler;\n"
    "@group(1) @binding(2) var ibl_brdf_lut : texture_2d<f32>;\n"
    "struct VertexInput {\n"
    "  @location(0) pos : vec3<f32>,\n"
    "  @location(1) nrm : vec3<f32>,\n"
    "  @location(2) m0 : vec3<f32>,\n"
    "  @location(3) m1 : vec3<f32>,\n"
    "  @location(4) m2 : vec3<f32>,\n"
    "  @location(5) m3 : vec3<f32>,\n"
    "  @location(6) color : vec4<f32>,\n"
    "  @location(7) metallic : f32,\n"
    "  @location(8) roughness : f32,\n"
    "  @location(9) emissive_strength : f32\n"
    "};\n"
    "struct VertexOutput {\n"
    "  @builtin(position) pos : vec4<f32>,\n"
    "  @location(0) color : vec4<f32>,\n"
    "  @location(1) normal : vec3<f32>,\n"
    "  @location(2) world_pos : vec3<f32>,\n"
    "  @location(3) metallic : f32,\n"
    "  @location(4) roughness : f32,\n"
    "  @location(5) emissive_strength : f32\n"
    "};\n"
    FLECS_ENGINE_SHADER_COMMON_SHARED_VERTEX_WGSL
    "@vertex fn vs_main(input : VertexInput) -> VertexOutput {\n"
    "  var out : VertexOutput;\n"
    "  let vertex = buildPbrVertexState(\n"
    "    input.pos,\n"
    "    input.nrm,\n"
    "    input.m0,\n"
    "    input.m1,\n"
    "    input.m2,\n"
    "    input.m3);\n"
    "  out.pos = vertex.clip_pos;\n"
    "  out.normal = vertex.world_normal;\n"
    "  out.world_pos = vertex.world_pos;\n"
    "  out.metallic = input.metallic;\n"
    "  out.roughness = input.roughness;\n"
    "  out.emissive_strength = input.emissive_strength;\n"
    "  out.color = input.color;\n"
    "  return out;\n"
    "}\n"
    FLECS_ENGINE_SHADER_COMMON_PBR_FUNCTIONS_WGSL
    "@fragment fn fs_main(input : VertexOutput) -> @location(0) vec4<f32> {\n"
    "  let albedo = input.color.rgb;\n"
    "  let metallic = clamp(input.metallic, 0.0, 1.0);\n"
    "  let roughness = clamp(input.roughness, 0.0, 1.0);\n"
    "  let direct_roughness = clamp(roughness, 0.045, 1.0);\n"
    "  let n = normalize(input.normal);\n"
    "  let light = getLightDirection();\n"
    "  let v = getViewDirection(input.world_pos);\n"
    "  let h = getHalfVector(v, light.dir);\n"
    "  let direct = computeDirectLighting(\n"
    "    n, v, light.dir, h,\n"
    "    albedo, metallic, direct_roughness,\n"
    "    light.enabled);\n"
    "  let ambient = computeAmbientLighting(albedo, metallic);\n"
    "  let f0 = computeF0(albedo, metallic);\n"
    "  let ndotv = saturate(dot(n, v));\n"
    "  let r = reflect(-v, n);\n"
    "  let max_mip = max(f32(textureNumLevels(ibl_prefiltered_env)) - 1.0, 0.0);\n"
    "  let lod = roughness * max_mip;\n"
    "  let prefiltered_color = textureSampleLevel(ibl_prefiltered_env, ibl_sampler, r, lod).rgb;\n"
    "  let brdf = textureSample(ibl_brdf_lut, ibl_sampler, vec2<f32>(ndotv, roughness)).rg;\n"
    "  let specular_ibl = prefiltered_color * computeSplitSumSpecularTerm(f0, brdf);\n"
    "  let emissive = albedo * max(input.emissive_strength, 0.0);\n"
    "  let lit_color = ambient + direct + specular_ibl + emissive;\n"
    "  return vec4<f32>(lit_color, input.color.a);\n"
    "}\n";

ecs_entity_t flecsEngine_shader_pbrColored(
    ecs_world_t *world)
{
    return flecsEngine_shader_ensure(world, "PbrColoredShader",
        &(FlecsShader){
            .source = kShaderSource,
            .vertex_entry = "vs_main",
            .fragment_entry = "fs_main"
        });
}
